version: 2

sources:
  - name: raw
    schema: lw_da_l17
    description: dataset for demo class
    tables:
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: price purchase

      - name: sales
        identifier: raw_gz_sales
        freshness:
          warn_after: { count: 90, period: day }
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"

      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: primary key
            tests:
              - not_null
              - unique
          - name: shipping_fee
            description: shipping fee
          - name: logcost
            description: cost of prep of ship
          - name: ship_cost
            description: cost paid per ship

  - name: rawg
    schema: lw_da_l18
    description: dataset for demo class
    tables:
      - name: facebook
        identifier: raw_gz_facebook

      - name: criteo
        identifier: raw_gz_criteo

      - name: bing
        identifier: raw_gz_bing

      - name: adwords
        identifier: raw_gz_adwords

models:
  - name: stg_raw__product
    description: stg raw product

  - name: stg_raw__sales
    description: stg raw sales

  - name: stg_raw__ship
    description: stg raw ship

  - name: int_sales_margin
    description: int sales margin

  - name: int_orders_margin
    description: int orders margin

  - name: int_orders_operational
    description: int orders operational margin

  - name: finance_days
    description: mart  Evolution Requests

  - name: stg_rawg__criteo
    description: stg rawg criteo

  - name: stg_rawg__bing
    description: stg rawg bing

  - name: stg_rawg__adwords
    description: stg rawg adworks

  - name: stg_rawg__facebook
    description: stg rawg facebook

  - name: int_campaigns
    description: int campaigns union

  - name: int_campaigns_day
    description: int campaigns by day

  - name: finance_campaigns_days
    description: global kpi days
    columns:
      - name: ads_margin
        description: operational_margin - ads_cost
      - name: average_basket
        description: average basket cost for each day
    tests:
      - not_null:
          column_name:
            - ads_margin
            - average_basket


  - name: finance_campaigns_month
    description: global kpi month
    columns:
      - name: ads_margin
        description: operational_margin - ads_cost
      - name: average_basket
        description: average basket cost for each month
    tests:
      - not_null:
          column_name:
            - ads_margin
            - average_basket


